app:
  lookout:
    logLevel: debug
    bblfshdConnectionString: ipv4://lookout-bblfshd:9432

image:
  lookout:
    repository: maartje/lookout

databases:
  postgres:
    cloudSQL: false
    dbConnectionString: postgresql://lookout:lookout@postgresql:5432/lookout

queues:
  rabbitmq:
    connectionString: amqp://lookout-rabbitmq-ha:5672

repositories:
  - url: github.com/meyskens/lookout

providers:
  github:
    app_id: 49140
    private_key: /local/lookout/private-key.pem
    secretName: lookout-github-key
    comment_footer: "_{{if .Feedback}}If you have feedback about this comment made by the analyzer {{.Name}}, please, [tell us]({{.Feedback}}){{else}}Comment made by the analyzer {{.Name}}{{end}}._"
    installation_sync_interval: 5m

analyzers:
  - name: terraform-analyzer
    addr: ipv4://lookout-terraform-analyzer:10303
    feedback: https://github.com/meyskens/lookout-terraform-analyzer/issues/new

bblfshd-sidecar:
  metrics:
    enabled: false
    namespace: lookout
    additionalServiceMatchLabels:
      app: lookout-work
  image:
    tag: v2.14.0
  drivers:
    install: true
    languages:
      # for js we have to lock old version due to style-analyzer
      javascript:
        repository: bblfsh/javascript-driver
        tag: v2.7.1
      # for the rest we can use latest
      python:
        repository: bblfsh/python-driver
        tag: v2.8.3
      cpp:
        repository: bblfsh/cpp-driver
        tag: v1.2.4
      java:
        repository: bblfsh/java-driver
        tag: v2.6.3
      bash:
        repository: bblfsh/bash-driver
        tag: v2.5.2
      ruby:
        repository: bblfsh/ruby-driver
        tag: v2.9.2
      go:
        repository: bblfsh/go-driver
        tag: v2.5.3
      csharp:
        repository: bblfsh/csharp-driver
        tag: v1.4.3
      php:
        repository: bblfsh/php-driver
        tag: v2.7.4
